### ISSUE TITLE
As note editor, I want to edit certain notes in monospace font.(eg: IT related note, commands, codes, etc)

### ISSUE THREAD

**Issue by siakhooi** [Automattic/simplenote-android#1539]
When taking note related to IT, commands, codes will be best to be edit in monospace font.
can it be detected like, when taking note in MD format?

### What
edit note in monospace font for some notes.

### Why
some contents are best display in monospace font, eg: computer related, commands, codes, etc.

### How
open for suggestion.

**Comment by wenfangdu** [comment]
I second this, I'm currently using the following css on the web version:

```css
* {
  font-family: Menlo, Monaco, 'Courier New', monospace;
}
```
